#!/bin/bash
export JPROFILER_HOME=/opt/jprofiler9

mvn clean package && $JAVA_HOME/bin/java -agentpath:$JPROFILER_HOME/bin/linux-x64/libjprofilerti.so=port=8849 -javaagent:$(pwd)/target/lib/perfcake-agent-7.5.jar -Xms256m -Xmx256m -jar target/sut-1.0-SNAPSHOT.jar

